//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullRouteRoutes
    {
        public int full_route_id { get; set; }
        public int airline_flight_id { get; set; }
        public Nullable<int> transfer_id { get; set; }
        public int index { get; set; }
        public int id { get; set; }
    
        public virtual FullRoute FullRoute { get; set; }
        public virtual ScheduledRoute ScheduledRoute { get; set; }
        public virtual Transfer Transfer { get; set; }
    }
}
