//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketClassDiscounts
    {
        public int id { get; set; }
        public int ticket_class_id { get; set; }
        public decimal value { get; set; }
    
        public virtual TicketClass TicketClass { get; set; }
    }
}
